=== arjunc12/personal/SolPicker/bin/solPicker/SolPickerSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
    <schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SolPickerSchema"
	xmlns:tns="http://www.example.org/SolPickerSchema" elementFormDefault="unqualified">
<!-- $Id: SolPickerSchema.xsd,v 1.2 2009/10/16 21:56:27 tizatt Exp $ -->
<!-- This schema defines the grammar for the input and output XML. It is enforced when the XML is parsed. -->
	<element name="SolPicker">
		<complexType>
			<sequence>
				<element name="oligoCount" type="int" minOccurs="0" maxOccurs="unbounded"/>
				<element name="Query" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="oligoLength" type="int" maxOccurs="1" minOccurs="1" default="60"/>
							<element name="oligoDistance" type="int" maxOccurs="1" minOccurs="0" default="60" />
							<element name="Domain">
								<complexType>
									<choice>
										<element name="Ensembl">
											<complexType>
												<sequence>
													<element
														name="Organism" maxOccurs="1" minOccurs="1"
														default="Homo_sapien">
														<simpleType>
															<restriction
																base="string">
																<minLength
																	value="1">
																</minLength>
															</restriction>
														</simpleType>
													</element>
													<element
														name="Chromosome" maxOccurs="1" minOccurs="1">
														<simpleType>
															<restriction
																base="string">
																<minLength
																	value="1">
																</minLength>
															</restriction>
														</simpleType>
													</element>
													<element name="startPosition" type="int" maxOccurs="1" minOccurs="1" />
													<element name="endPosition" type="int" maxOccurs="1" minOccurs="1" />
												</sequence>
											</complexType>
										</element>
										<element name="UCSC">
											<complexType>
												<sequence>
													<element
														name="Organism" default="hg18">
														<simpleType>
															<restriction
																base="string">
																<minLength
																	value="1">
																</minLength>
															</restriction>
														</simpleType>
													</element>
													<element
														name="Chromosome" maxOccurs="1" minOccurs="1">
														<simpleType>
															<restriction
																base="string">
																<minLength
																	value="1">
																</minLength>
															</restriction>
														</simpleType>
													</element>
													<element name="startPosition" type="int" maxOccurs="1" minOccurs="1" />
													<element name="endPosition" type="int" maxOccurs="1" minOccurs="1" />
													<element name="Padding5" type="int" maxOccurs="1" default="0"/>
													<element name="Padding3" type="int" maxOccurs="1" default="0"/>
												</sequence>
											</complexType>
										</element>
									</choice>
								</complexType>
							</element>
						</sequence>
						<attribute name="QueryName" type="ID" use="required">
						</attribute>
					</complexType>
					<unique name="QueryName">
						<selector xpath="Query"/>
						<field xpath="@QueryName"/>
					</unique>
				</element>
				<element name="Configuration" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="Filter" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="Parameter" minOccurs="1" maxOccurs="unbounded">
											<complexType>
												<attribute
													name="Constraint">
													<simpleType>
														<restriction
															base="string">
															<minLength
																value="1">
															</minLength>
														</restriction>
													</simpleType>
												</attribute>
												<attribute
													name="Value">
													<simpleType>
														<restriction
															base="string">
															<minLength
																value="1">
															</minLength>
														</restriction>
													</simpleType>
												</attribute>
											</complexType>
										</element>							
									</sequence>
									<attribute name="Type" type="string" use="required"/>
								</complexType>
							</element>			
						</sequence>
						<attribute name="ConfigID" type="ID" use="required">
						</attribute>
					</complexType>
					<unique name="ConfigurationID">
						<selector xpath="Configuration"/>
						<field xpath="@ConfigID"/>
					</unique>
				</element>				
				<element name="Job" minOccurs="1" maxOccurs="unbounded">
					<complexType>
						<attribute name="JobID" type="int" use="required">
						</attribute>
						<attribute name="QueryName" type="IDREF" use="required">
						</attribute>
						<attribute name="ConfigID" type="IDREF" use="required">
						</attribute>
					</complexType>
					<unique name="JobID">
						<selector xpath="Job"/>
						<field xpath="@JobID"/>
					</unique>
				</element>			
			</sequence>
		</complexType>
	</element>
</schema>

=== arjunc12/personal/SolPicker/bin/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<SolPicker xmlns="http://www.example.org/SolPickerSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SolPickerSchema SolPickerSchema.xsd ">
<Query QueryName="1">
<oligoLength>60</oligoLength>
<oligoDistance>1</oligoDistance>
<Domain>
<UCSC>
<Organism>Homo_sapiens</Organism>
<Chromosome>3</Chromosome>
<startPosition>5600</startPosition>
<endPosition>7000</endPosition>
</UCSC>
</Domain>
</Query>
<Job ConfigID="1" JobID="1" QueryName="1"/>
</SolPicker>

=== arjunc12/personal/SolPicker/bin/solPicker/test1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:SolPicker xmlns:tns="http://www.example.org/SolPickerSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SolPickerSchema SolPickerSchema.xsd ">
  <Query QueryName="name">
    <oligoLength>60</oligoLength>
    <Domain>
      <Ensembl>
        <Chromosome>7</Chromosome>
        <startPosition>145610000</startPosition>
        <endPosition>145650000</endPosition>
      </Ensembl>
    </Domain>
  </Query>
  <Configuration ConfigID="id">
    <Filter Type="">
      <Parameter/>
    </Filter>
  </Configuration>
  <Job ConfigID="id" JobID="0" QueryName="name"/>
</tns:SolPicker>

=== arjunc12/personal/SolPicker/XML/test2.xml
<?xml version="1.0" encoding="UTF-8"?>
<SolPicker xmlns="http://www.example.org/SolPickerSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SolPickerSchema SolPickerSchema.xsd ">
  <Query QueryName="test2">
    <oligoLength>100</oligoLength>
    <oligoDistance>1</oligoDistance>
    <Domain>
      <UCSC>
        <Organism>hg18</Organism>
        <Chromosome>3</Chromosome>
        <startPosition>0</startPosition>
        <endPosition>0</endPosition>
        <Padding5>0</Padding5>
        <Padding3>0</Padding3>
      </UCSC>
    </Domain>
  </Query>
  <Configuration ConfigID="3">
    <Filter Type="lowercase">
      <Parameter Constraint="max" Value="5"/>
    </Filter>
  </Configuration>
  <Job ConfigID="3" JobID="1" QueryName="test2"/>
</SolPicker>

=== arjunc12/personal/SolPicker/bin/solPicker/SolPickerSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:SolPicker xmlns:tns="http://www.example.org/SolPickerSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SolPickerSchema SolPickerSchema.xsd ">
  <Query QueryName="test">
    <oligoLength>60</oligoLength>
    <Domain>
      <Ensembl>
        <Chromosome>3</Chromosome>
        <startPosition>65000</startPosition>
        <endPosition>65100</endPosition>
      </Ensembl>
    </Domain>
  </Query>
  <Configuration ConfigID="name">
    <Filter Type="lowercase">
      <Parameter Constraint = "max" Value = "30"/> 
    </Filter>
  </Configuration>
  <Job ConfigID="name" JobID="0" QueryName="test"/>
</tns:SolPicker>

=== arjunc12/personal/SolPicker/XML/test3.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:SolPicker xmlns:tns="http://www.example.org/SolPickerSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/SolPickerSchema SolPickerSchema.xsd ">
  <Query QueryName="second">
    <oligoDistance>1</oligoDistance>
    <oligoLength>60</oligoLength>
    <Domain>
      <Ensembl>
        <Chromosome>7</Chromosome>
        <startPosition>145610000</startPosition>
        <endPosition>145650000</endPosition>
      </Ensembl>
    </Domain>
  </Query>
  <Configuration ConfigID="first">
    <Filter Type="lowercase">
      <Parameter Constraint="max" Value="20"/>
    </Filter>
  </Configuration>
  <Job ConfigID="first" JobID="1" QueryName="second"/>
</tns:SolPicker>
